version: '2.3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: retcad
    runtime: nvidia
    volumes:
      - .:/retcad
    ports:
      - "8000:8000"